name: Renovate Development
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - ".github/renovate*"
      - ".github/workflows/renovate*"
  push:
    branches:
      - "main"
    paths:
      - ".github/renovate*"
      - ".github/workflows/renovate*"
jobs:
  renovate-dryrun:
    runs-on: ubuntu-latest
    steps:
    - name: Token
      id: generate_token
      uses: tibdex/github-app-token@v1.8.0
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PEM }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate Dry Run
      run: |
        jq '.dryRun = "true"' .github/renovate.json > .github/renovate.json.tmp
        mv -f .github/renovate.json.tmp .github/renovate.json
        jq '.baseBranches = ["${{ github.head_ref }}"]' .github/renovate.json > .github/renovate.json.tmp
        mv -f .github/renovate.json.tmp .github/renovate.json

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v34.154.1
      with:
        configurationFile: .github/renovate.json
        token: 'x-access-token:${{ steps.generate_token.outputs.token }}'
      env:
        LOG_LEVEL: "debug"
        RENOVATE_DRY_RUN: full
