name: Renovate Development
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - ".github/renovate*"
      - ".github/workflows/renovate*"
  push:
    branches:
      - "main"
    paths:
      - ".github/renovate*"
      - ".github/workflows/renovate*"
jobs:
  renovate-dryrun:
    runs-on: ubuntu-latest
    steps:
    - name: Get token
      id: get_token
      uses: machine-learning-apps/actions-app-token@0.21
      with:
        APP_PEM: ${{ secrets.APP_PEM }}
        APP_ID: ${{ secrets.APP_ID }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate Dry Run
      run: |
        jq '.dryRun = "true"' .github/renovate.json > .github/renovate.json.tmp
        mv -f .github/renovate.json.tmp .github/renovate.json
        jq '.baseBranches = ["${{ github.head_ref }}"]' .github/renovate.json > .github/renovate.json.tmp
        mv -f .github/renovate.json.tmp .github/renovate.json

    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v34.154.1
      with:
        configurationFile: .github/renovate.json
        token: "x-access-token:${{ steps.get_token.outputs.app_token }}"
      env:
        LOG_LEVEL: "debug"
        RENOVATE_DRY_RUN: full
