
name: Renovate
on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - 'main'
    paths:
      - '.github/renovate*'
      - '.github/workflows/renovate*'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
    - name: Get token
      id: get_token
      uses: machine-learning-apps/actions-app-token@0.21
      with:
        APP_PEM: ${{ secrets.APP_PEM }}
        APP_ID: ${{ secrets.APP_ID }}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Self-hosted Renovate
      uses: renovatebot/github-action@v34.154.1
      with:
        configurationFile: .github/renovate.json
        token: "x-access-token:${{ steps.get_token.outputs.app_token }}"
      env:
        LOG_LEVEL: "debug"
        RENOVATE_PLATFORM: github
